# Generated by Django 3.1.7 on 2021-05-23 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('yazi', models.TextField()),
                ('tur', models.CharField(choices=[('1', 'Korku'), ('2', 'Gezi'), ('3', 'Hayata Dair')], max_length=10)),
                ('kayitzaman', models.DateTimeField(default=django.utils.timezone.now)),
                ('yayimzaman', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
